unique_ids:
  forms: {processwin: PLRHP32GA3W6G2OUPXQV3CC3HWZWOC4Q, processwords: 2XQPWMHG3VUIYRSMBNW7MBXR3IRXRSQV,
    rules: 3LDK5AGF642Y3MNVG6LWZAJ4AZSVT4IY, startgame: MCUYK2DH4WAVNBRJEEUB5Z5DTO3WZPIV}
  modules: {}
  server_modules: {ServerModule1: G5YDV7QD3HWV5FGJFKLT6EYGCASPANYL}
  assets: {standard-page.html: LE4EIY6FHUJ7YLOMQ4H6CPOR47E2ERSG, theme.css: VEG2K7UPSZ2KFQIERZ4AGCJGTH7IB22F}
